Imports butika.Models

Public Class adminMockData
    Public Function GetMockAccounts() As List(Of Account)
        'Return New List(Of Account) From {
        '    New Account With {.UserID = 1, .FullName = "John Doe", .UserName = "johndoe", .FirstName = "John", .MiddleName = "A.", .LastName = "Doe", .Email = "johndoe@example.com", .Password = "password123", .Contact = "1234567890", .BirthDate = New DateTime(1990, 5, 12), .Status = "Active", .DateJoined = "2024-03-01"},
        '    New Account With {.UserID = 2, .FullName = "Jane Smith", .UserName = "janesmith", .FirstName = "Jane", .MiddleName = "B.", .LastName = "Smith", .Email = "janesmith@example.com", .Password = "password123", .Contact = "0987654321", .BirthDate = New DateTime(1985, 8, 24), .Status = "Inactive", .DateJoined = "2023-12-15"},
        '    New Account With {.UserID = 3, .FullName = "Alice Johnson", .UserName = "alicej", .FirstName = "Alice", .MiddleName = "C.", .LastName = "Johnson", .Email = "alicej@example.com", .Password = "password123", .Contact = "5551234567", .BirthDate = New DateTime(1992, 7, 10), .Status = "Active", .DateJoined = "2025-01-10"},
        '    New Account With {.UserID = 4, .FullName = "Bob Brown", .UserName = "bobbyb", .FirstName = "Bob", .MiddleName = "D.", .LastName = "Brown", .Email = "bobbrown@example.com", .Password = "password123", .Contact = "3334445555", .BirthDate = New DateTime(1988, 2, 5), .Status = "Active", .DateJoined = "2022-09-20"},
        '    New Account With {.UserID = 5, .FullName = "Charlie White", .UserName = "charliew", .FirstName = "Charlie", .MiddleName = "E.", .LastName = "White", .Email = "charliew@example.com", .Password = "password123", .Contact = "6667778888", .BirthDate = New DateTime(1995, 11, 30), .Status = "Inactive", .DateJoined = "2025-05-25"},
        '    New Account With {.UserID = 6, .FullName = "David Green", .UserName = "dgreen", .FirstName = "David", .MiddleName = "F.", .LastName = "Green", .Email = "dgreen@example.com", .Password = "password123", .Contact = "7778889999", .BirthDate = New DateTime(1983, 4, 15), .Status = "Active", .DateJoined = "2024-02-14"},
        '    New Account With {.UserID = 7, .FullName = "Emma Black", .UserName = "emblack", .FirstName = "Emma", .MiddleName = "G.", .LastName = "Black", .Email = "emblack@example.com", .Password = "password123", .Contact = "4445556666", .BirthDate = New DateTime(1997, 9, 22), .Status = "Inactive", .DateJoined = "2023-06-18"},
        '    New Account With {.UserID = 8, .FullName = "Frank Gray", .UserName = "fgray", .FirstName = "Frank", .MiddleName = "H.", .LastName = "Gray", .Email = "fgray@example.com", .Password = "password123", .Contact = "2223334444", .BirthDate = New DateTime(1991, 1, 3), .Status = "Active", .DateJoined = "2022-11-05"},
        '    New Account With {.UserID = 9, .FullName = "Grace Blue", .UserName = "gblue", .FirstName = "Grace", .MiddleName = "I.", .LastName = "Blue", .Email = "gblue@example.com", .Password = "password123", .Contact = "9990001111", .BirthDate = New DateTime(1994, 6, 12), .Status = "Inactive", .DateJoined = "2023-08-22"},
        '    New Account With {.UserID = 10, .FullName = "Henry White", .UserName = "hwhite", .FirstName = "Henry", .MiddleName = "J.", .LastName = "White", .Email = "hwhite@example.com", .Password = "password123", .Contact = "8889990000", .BirthDate = New DateTime(1989, 12, 25), .Status = "Active", .DateJoined = "2025-03-05"},
        '    New Account With {.UserID = 11, .FullName = "Isabella Brown", .UserName = "isbrown", .FirstName = "Isabella", .MiddleName = "K.", .LastName = "Brown", .Email = "isbrown@example.com", .Password = "password123", .Contact = "1112223333", .BirthDate = New DateTime(1996, 3, 18), .Status = "Active", .DateJoined = "2023-07-10"},
        '    New Account With {.UserID = 12, .FullName = "Jack Wilson", .UserName = "jwilson", .FirstName = "Jack", .MiddleName = "L.", .LastName = "Wilson", .Email = "jwilson@example.com", .Password = "password123", .Contact = "5556667777", .BirthDate = New DateTime(1993, 5, 14), .Status = "Inactive", .DateJoined = "2022-10-30"},
        '    New Account With {.UserID = 13, .FullName = "Kate Miller", .UserName = "kmiller", .FirstName = "Kate", .MiddleName = "M.", .LastName = "Miller", .Email = "kmiller@example.com", .Password = "password123", .Contact = "3332221111", .BirthDate = New DateTime(1987, 8, 8), .Status = "Active", .DateJoined = "2025-01-20"},
        '    New Account With {.UserID = 14, .FullName = "Leo Harris", .UserName = "leoharris", .FirstName = "Leo", .MiddleName = "N.", .LastName = "Harris", .Email = "leoharris@example.com", .Password = "password123", .Contact = "7778880000", .BirthDate = New DateTime(1992, 11, 5), .Status = "Inactive", .DateJoined = "2023-09-10"},
        '    New Account With {.UserID = 15, .FullName = "Megan Clark", .UserName = "megclark", .FirstName = "Megan", .MiddleName = "P.", .LastName = "Clark", .Email = "megclark@example.com", .Password = "password123", .Contact = "4445558888", .BirthDate = New DateTime(1998, 12, 16), .Status = "Active", .DateJoined = "2025-03-18"},
        '    New Account With {.UserID = 16, .FullName = "Nathan Scott", .UserName = "nathanscott", .FirstName = "Nathan", .MiddleName = "Q.", .LastName = "Scott", .Email = "nathanscott@example.com", .Password = "password123", .Contact = "9991112222", .BirthDate = New DateTime(1989, 9, 30), .Status = "Inactive", .DateJoined = "2022-12-22"},
        '    New Account With {.UserID = 17, .FullName = "Olivia Davis", .UserName = "oliviad", .FirstName = "Olivia", .MiddleName = "R.", .LastName = "Davis", .Email = "oliviadavis@example.com", .Password = "password123", .Contact = "5559996666", .BirthDate = New DateTime(1994, 10, 21), .Status = "Active", .DateJoined = "2024-01-25"},
        '    New Account With {.UserID = 18, .FullName = "Paul Lewis", .UserName = "paullewis", .FirstName = "Paul", .MiddleName = "S.", .LastName = "Lewis", .Email = "paullewis@example.com", .Password = "password123", .Contact = "2224445555", .BirthDate = New DateTime(1991, 2, 13), .Status = "Inactive", .DateJoined = "2023-04-12"},
        '    New Account With {.UserID = 19, .FullName = "Quincy King", .UserName = "quincyking", .FirstName = "Quincy", .MiddleName = "T.", .LastName = "King", .Email = "quincyking@example.com", .Password = "password123", .Contact = "8882223333", .BirthDate = New DateTime(1996, 7, 7), .Status = "Active", .DateJoined = "2023-11-09"},
        '    New Account With {.UserID = 20, .FullName = "Rachel Adams", .UserName = "racheladams", .FirstName = "Rachel", .MiddleName = "U.", .LastName = "Adams", .Email = "racheladams@example.com", .Password = "password123", .Contact = "1114445555", .BirthDate = New DateTime(1995, 5, 25), .Status = "Inactive", .DateJoined = "2023-01-30"},
        '    New Account With {.UserID = 21, .FullName = "Steven Mitchell", .UserName = "stevenmitchell", .FirstName = "Steven", .MiddleName = "V.", .LastName = "Mitchell", .Email = "stevenmitchell@example.com", .Password = "password123", .Contact = "9995557777", .BirthDate = New DateTime(1992, 4, 19), .Status = "Active", .DateJoined = "2025-03-17"},
        '    New Account With {.UserID = 22, .FullName = "Tina Harris", .UserName = "tina_harris", .FirstName = "Tina", .MiddleName = "W.", .LastName = "Harris", .Email = "tina@example.com", .Password = "password123", .Contact = "4442221111", .BirthDate = New DateTime(1986, 10, 3), .Status = "Inactive", .DateJoined = "2024-05-13"},
        '    New Account With {.UserID = 23, .FullName = "Ursula Young", .UserName = "ursulayang", .FirstName = "Ursula", .MiddleName = "X.", .LastName = "Young", .Email = "ursula@example.com", .Password = "password123", .Contact = "8885554444", .BirthDate = New DateTime(1990, 12, 28), .Status = "Active", .DateJoined = "2024-02-22"},
        '    New Account With {.UserID = 24, .FullName = "Victor Nelson", .UserName = "victornelson", .FirstName = "Victor", .MiddleName = "Y.", .LastName = "Nelson", .Email = "victor@example.com", .Password = "password123", .Contact = "7776665555", .BirthDate = New DateTime(1993, 6, 9), .Status = "Inactive", .DateJoined = "2023-08-13"},
        '    New Account With {.UserID = 25, .FullName = "Wendy Parker", .UserName = "wendyparker", .FirstName = "Wendy", .MiddleName = "Z.", .LastName = "Parker", .Email = "wendy@example.com", .Password = "password123", .Contact = "6665554444", .BirthDate = New DateTime(1988, 3, 15), .Status = "Active", .DateJoined = "2024-07-20"},
        '    New Account With {.UserID = 26, .FullName = "Xander Reed", .UserName = "xanderreed", .FirstName = "Xander", .MiddleName = "AA.", .LastName = "Reed", .Email = "xander@example.com", .Password = "password123", .Contact = "5554443333", .BirthDate = New DateTime(1999, 1, 29), .Status = "Inactive", .DateJoined = "2023-11-01"},
        '    New Account With {.UserID = 27, .FullName = "Yasmine Foster", .UserName = "yasminefoster", .FirstName = "Yasmine", .MiddleName = "BB.", .LastName = "Foster", .Email = "yasmine@example.com", .Password = "password123", .Contact = "4443332222", .BirthDate = New DateTime(1994, 4, 6), .Status = "Active", .DateJoined = "2023-03-10"},
        '    New Account With {.UserID = 28, .FullName = "Zane Bell", .UserName = "zanebell", .FirstName = "Zane", .MiddleName = "CC.", .LastName = "Bell", .Email = "zane@example.com", .Password = "password123", .Contact = "3332221111", .BirthDate = New DateTime(1992, 8, 2), .Status = "Inactive", .DateJoined = "2024-02-18"},
        '    New Account With {.UserID = 29, .FullName = "Abby Morgan", .UserName = "abbymorgan", .FirstName = "Abby", .MiddleName = "DD.", .LastName = "Morgan", .Email = "abby@example.com", .Password = "password123", .Contact = "2221110000", .BirthDate = New DateTime(1997, 9, 28), .Status = "Active", .DateJoined = "2023-11-03"},
        '    New Account With {.UserID = 30, .FullName = "Blake Carter", .UserName = "blakecarter", .FirstName = "Blake", .MiddleName = "EE.", .LastName = "Carter", .Email = "blake@example.com", .Password = "password123", .Contact = "9990001111", .BirthDate = New DateTime(1990, 7, 12), .Status = "Inactive", .DateJoined = "2023-10-29"}
        '}
        Return Nothing
    End Function


End Class
